import type { Metadata } from "next";
import { Inter } from "next/font/google";
// import "./globals.css";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter";
import { ThemeProvider } from '@mui/material/styles';
import theme from "@/theme";

const Header = () => {
  return <header>Content from Header</header>
};

const Footer = () => {
  return <header>Content from Footer</header>
};

const inter = Inter({ subsets: [ "latin" ] });

export const metadata: Metadata = {
  title: "Create Next App Edited",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly <{
  children: React.ReactNode;
}>){
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppRouterCacheProvider>
          <ThemeProvider theme={theme}>
            <Header />
              { children }
            <Footer />
          </ThemeProvider>
        </AppRouterCacheProvider>
        </body>
    </html>
  );
}
